# Changes here will be overwritten by Copier
_commit: a967b29
_src_path: gh:entangled/template-mkdocs
project_author: Johan Hidding <johannes.hidding@gmail.com>
project_name: aoc2023
project_title: Advent of Code 2023
