# ~/~ begin <<docs/index.md#brei.toml>>[init]
include = [".entangled/tasks.json"]

[runner.julia]
command = "julia"
args = [
  "--project=workenv",
  "--startup-file=no",
  "-O0",
  "-e",
  "using DaemonMode; runargs()",
  "${script}",
]

[[task]]
name = "repl"
script = "julia --project=workenv -e 'using Revise' -i"

[[task]]
name = "julia-daemon"
script = "julia --project=workenv --startup-file=no -e 'using Revise; using DaemonMode; serve()'"

[[task]]
name = "test"
script = "julia --project=. -e 'using Pkg; Pkg.test()'"

[template.run-day]
name = "day${day}"
runner = "julia"
requires = ["input/day${day}.txt", "src/Day${day}.jl"]
stdout = "output/day${day}.txt"
script = """
using AOC2023.Day${day}

open("input/day${day}.txt", "r") do f_in
    Day${day}.main(f_in)
end
println()
"""

[[call]]
template = "run-day"
collect = "run"
[call.args]
day = [
  "01",
  "02",
  "03",
  "04",
  "05",
  "06",
  "07",
  "08",
  "09",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
]
# ~/~ end
